name: pick-place-occlusion

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - python-dotenv
  - pip:
      - google-genai
      - openai
      - ollama
      - ultralytics
      - dotenv
